//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int studentid { get; set; }
        public string aridno { get; set; }
        public string name { get; set; }
        public string fathername { get; set; }
        public string section { get; set; }
        public string degree { get; set; }
        public string city { get; set; }
        public int semester { get; set; }
        public string Profileimage { get; set; }
    }
}
